name: tlbb_app
description: "天龙亿旧 - 经典网游怀旧图鉴攻略"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  shared_preferences: ^2.5.0
  device_info_plus: ^11.0.0
  url_launcher: ^6.3.0
  crypto: ^3.0.6
  flutter_markdown: ^0.7.4
  share_plus: ^11.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icons/beasts/
    - assets/icons/beasts/emei/
    - assets/icons/beasts/gaibang/
    - assets/icons/beasts/mingjiao/
    - assets/icons/beasts/murong/
    - assets/icons/beasts/shaolin/
    - assets/icons/beasts/tianlong/
    - assets/icons/beasts/tianshan/
    - assets/icons/beasts/wudang/
    - assets/icons/beasts/xiaoyao/
    - assets/icons/beasts/xingxiu/
    - assets/icons/gems/
    - assets/icons/items/
    - assets/icons/sets/
    - assets/icons/sets/digong/
    - assets/icons/sets/gumu/
    - assets/icons/sets/menpai/
    - assets/icons/sets/piaomiao/
    - assets/icons/sets/shaoshi/
    - assets/icons/sets/xinshou/
    - assets/icons/sets/xuanhao/
    - assets/icons/sets/yuci/
